name: Second workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  issues:
    types: opened
env:
  TEST_VAR: thisIsExampleVarWorkflow
  MY_USER: ${{ vars.MY_USER }}
  MY_ENV_SECRET: ${{ secrets.MY_ENV_SECRET }}
jobs:
  Script-1:
    runs-on: ubuntu-latest
    environment: dev
    outputs: 
      statement: ${{ steps.step3.outputs.statement }}
    env:
      TEST_VAR_1: JobWorkflowVar
    steps: 
    - name: Checkout step
      uses: actions/checkout@v4  
    - name: Job Starts
      run: echo "-------------- JOB BEGINS!-----------"
    - name: Script 01 executing!
      id: step3
      run: |
        bash ./Scripts/script01.sh
        cat file01.txt
        echo "statement=ghjkhasduh@344342^342ehsu" >> $GITHUB_OUTPUT
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: imp-file
        path: file01.txt
    - name: Printing vars
      run: |
        echo "$TEST_VAR"
        echo "$TEST_VAR_1"
        echo "$MY_USER"
        echo "$MY_ENV_SECRETt" #typo to make this step fail
    - name: Printing vars - check point
      if: success()
      run: echo "Vars are printed"
    - name: Job accomplished step
      run: echo "-------------- JOB DONE!--------------"
  Script-2:
      needs: Script-1
      if: failure() #this job should run only when script-1 job fails
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout step
        uses: actions/checkout@v4  
      - name: Job Starts
        run: echo "-------------- JOB BEGINS!-----------"
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: imp-file
      - name: Script 01 executing!
        run: |
          export MY_VAR="${{ needs.Script-1.outputs.statement }}"
          bash ./Scripts/script02.sh
          cat file01.txt
      - name: Printing vars - job2 ###
        run: |
          echo "$TEST_VAR"
          echo "${{ secrets.MY_SECRET }}"    
      - name: Job accomplished step
        run: echo "-------------- JOB DONE!--------------"
        
