name: Second workflow
on:
    - push
    - workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
   # - name: Checkout step
     # uses: actions/checkout@v4  
    - name: List the items
      run: ls -lrth ./Scripts
    - name: Multi line commands
      run: bash ./Scripts/script01.sh
    - name: List the items
      run: ls -lrth 
