name: Second workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  issues:
    types: opened
jobs:
  Script-1:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout step
      uses: actions/checkout@v4  
    - name: Job Starts
      run: echo "-------------- JOB BEGINS!-----------"
    - name: Script 01 executing!
      run: |
        bash ./Scripts/script01.sh
        cat file01.txt
    - name: Job accomplished step
      run: echo "-------------- JOB DONE!--------------"
  Script-2:
      needs: Script-1
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout step
        uses: actions/checkout@v4  
      - name: Job Starts
        run: echo "-------------- JOB BEGINS!-----------"
      - name: Script 01 executing!
        run: |
          bash ./Scripts/script02.sh
          cat file01.txt
      - name: Job accomplished step
        run: echo "-------------- JOB DONE!--------------"
        #comment to test the push
