name: A reusable example
on: 
    push:
        branches:
            - reuse
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: --Version check--
              run: cat /etc/os*
    Call-code:
        uses: ./.github/workflows/reusable.yml
        with:
            name: aws-ghaction-user-101
    # pull-result-code:
    #     uses: ./.github/workflows/reusable.yml
    Check-result-code:
        runs-on: ubuntu-latest
        needs: Call-code
        steps:
            - name: Printing result code
              run: echo "${{ needs.Call-code.outputs.final-result-code }}"

