name: Concurrency check
on:
    push:
        branches:
            [concurrency]
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Push count
              run: echo "This is push no. 1"
            - name: Go to sleep
              run: sleep 300
