name: THis is Reusable code - to print user name
on:
    workflow_call:
        inputs:
            name:
                #required: true
                default: admin-user
                type: string
        outputs:
            final-result-code: 
                value: ${{ jobs.job2.outputs.result-code }}
        secrets:
            TOKEN_NUM:
                required: true
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Print user name
              run: echo "${{ inputs.name }}"
    job2:
        needs: job1
        runs-on: ubuntu-latest
        outputs:
            result-code: ${{ steps.code.outputs.result }}
        steps:
            - name: Return result code
              id: code
              run: echo "result=0 < SUCCESS >" >> $GITHUB_OUTPUT
    job3:
        needs: job2
        runs-on: ubuntu-latest
        steps:
            - name: secret
              env:
                TOKEN_NO: ${{ secrets.TOKEN_NUM }}
              run: echo "Secrets job - ${{ env.TOKEN_NO }}"

