name: "Composite action file"
description: " Runs multiple steps"
inputs:
  username:
    default: "Default"
   
runs:
  using: composite
  steps:
    - run: echo "------------------------------------"
      shell: bash
    - run: echo " This is user name ${{ inputs.username }}"
      shell: bash
    - run: echo "------------------------------------"
      shell: bash

